config/routes.rb
Rails.application.routes.draw do
  get 'checkout/customer'
  post 'checkout/customer', to: 'checkout#customer_new', as: :new_checkout_customer

  get 'checkout/payment/:order', to: 'checkout#payment', as: :checkout_payment
  post 'checkout/payment', to: 'checkout#payment_new', as: :create_checkout_payment

  get 'checkout/confirm/:payment_id', to: 'checkout#confirm', as: :checkout_confirm

  post 'checkout/confirm/nofifications', to: 'checkout#update_confirm', as: :update_checkout_confirm

  root to: "catalog#index"

  post '/', to: "catalog#movement"
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/checkout.rb
class Checkout
  def initialize
    auth = Moip2::Auth::Basic.new(ENV['MOIP_TOKEN'], ENV['MOIP_SECRET'])
    client = Moip2::Client.new(:sandbox, auth)
    @api = Moip2::Api.new(client)
  end

  def create_order(order, customer, total_discount, total_addition = 0)
    item_ids ||= []
    order.product_movements.each do |item|
      item_ids << item.product_id;
    end

    products = Product.find(item_ids)

    items ||= []
    products.each do |item|
      items << {
        product: item.product_name,
        quantity: 1,
        detail: item.detail,
        price: item.price
      }
    end

    order_json = {
      own_id: order.id,
      amount: {
        subtotals: {
          discount: total_discount,
          addition: total_addition
        }
      },
      items: items,
      customer: {
        own_id: customer.id,
        fullname: customer.fullname,
        email: customer.email,
      }
    }

    @api.order.create(order_json)
  end

  def show_order(order_id)
    @api.order.show(order_id)
  end

  def create_payment(order, payment)
    credit_card_payment = {
      installment_count: payment[:instalment_count].to_i,
      funding_instrument: {
        method: "CREDIT_CARD",
         credit_card: {
         expiration_month: payment[:expiration_month],
         expiration_year: payment[:expiration_year],
         number: payment[:card_number],
         cvc: payment[:cvc],
           holder: {
             fullname: payment[:holder_name],
             birthdate: "#{payment['holder_birthdate(1i)']}-#{payment['holder_birthdate(2i)']}-#{payment['holder_birthdate(3i)']}",
             tax_document: {
               type: "CPF",
               number: payment[:cpf]
             },
              phone: {
                country_code: "55",
                area_code: "11",
                number: payment[:phone]
              }
            }
          }
        }
      }

      @api.payment.create(order.external_id, credit_card_payment)
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def customer
    products = cookies[:cart]
    product_movements = JSON.parse products
    product_ids ||= []
    product_movements.each do |item|
      product_ids << item['product_id']
    end

    @coupons = Coupon.all
    @products = Product.find(product_ids)
  end

  def customer_new
    products_cart = cookies[:cart]
    product_movements = JSON.parse products_cart

    customer = Customer.new(customer_params);
    customer.save

    order = customer.orders.create()

    total_price = 0
    product_movements.each do |item|
      product = Product.find(item['product_id'])
      order.product_movements.create(product_id: item['product_id'], quantity: item['quantity'], status: "SUSPENDED")
      product.update(quantity: product.quantity - item['quantity'])
      total_price += product.price
    end

    if coupon = Coupon.where(code: params[:coupon]).first
      total_discount = handle_value coupon.discount, total_price
    end

    checkout = Checkout.new
    order_response = checkout.create_order(order, customer, total_discount)
    order.update(external_id: order_response.id)
    customer.update(external_id: order_response.customer.id)

    redirect_to checkout_payment_path(order.id)
  end

  def payment
    checkout = Checkout.new
    @order = Order.find(params[:order])
    @order_response = checkout.show_order(@order.external_id)
    payment = Payment.new(order_id: params[:order], status: "ORDERED", amount: @order_response.amount)
    payment.save
  end

  def payment_new
    order = Order.find(payment_params[:order])
    payment = Payment.where(order_id: payment_params[:order]).first
    customer = Customer.find(order.customer_id)

    payment.instalment_count = payment_params[:instalment_count]
    payment.funding_instrument = "CREDIT_CARD"

    checkout = Checkout.new

    if payment_params[:instalment_count].to_i > 1
      payment.amount['subtotals']['addition'] = handle_value Payment::INSTALMENT_TAX, payment.amount['total']
      payment.amount['total'] = payment.amount['total'] + payment.amount['subtotals']['addition']

      order_response = checkout.create_order(order, customer, payment.amount['subtotals']['discount'], payment.amount['subtotals']['addition'])
      order.update(external_id: order_response.id)
      payment_response = checkout.create_payment(order, payment_params)
    else
      payment_response = checkout.create_payment(order, payment_params)
    end

    if payment.update(external_id: payment_response.id, status: payment_response.status)
      redirect_to checkout_confirm_path(payment.id)
    end
  end

  def confirm
    @payment = Payment.find(params[:payment_id])
    order = Order.find(@payment.order_id)

    product_ids ||= []
    order.product_movements.each do |order|
      product_ids << order.product_id
    end

    @order = order
    @customer = Customer.find(order.customer_id)
    @product = Product.find(product_ids)
  end

  def update_confirm
    resources = params[:resource];

    if resources[:payment][:id]
      payment = Payment.where(external_id: resources[:payment][:id])
    end

    payment.update(status: resources[:payment][:status])
  end

  def handle_value(handle, total)
    ((handle * (total.to_f/100))*100).to_i
  end

  def payment_params
    params.require(:payment).permit(:card_number, :holder_name, :cvc, :expiration_month, :expiration_year, :holder_birthdate, :cpf, :phone, :instalment_count, :order)
  end

  def customer_params
    params.require(:customer).permit(:fullname, :email, :phone, :birth_date, :tax_document)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/_form.html.erb
<div class="columns medium-6 card end">
  <%= form_for :customer do |f| %>
    <div class="field">
      <%= f.label "Nome Completo", class: "text-subhead" %>
      <%= f.text_field :fullname %>
    </div>

    <div class="field">
      <%= f.label "E-mail", class: "text-subhead" %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label "Telefone", class: "text-subhead" %>
      <%= f.text_field :phone %>
    </div>

    <div class="field">
      <%= f.label "Nascimento", class: "text-subhead" %>
      <%= f.text_field :birth_date %>
    </div>

    <div class="field">
      <%= f.label "CPF", class: "text-subhead" %>
      <%= f.text_field :tax_document %>
    </div>

    <div class="actions">
      <%= f.submit 'Salvar', class: 'raised-button ink' %>
    </div>
  <% end %>
</div>

app/views/checkout/_form_card.html.erb
<div class="row columns end">
  <%= form_for :payment, url: create_checkout_payment_path do |f| %>
    <div class="field">
      <%= f.label "Número do Cartão", class: "text-subhead" %>
      <%= f.text_field :card_number, maxlength: 16 %>
    </div>

    <div class="row">
      <div class="field columns medium-4">
        <%= f.label "Mês", class: "text-subhead" %>
        <%= f.text_field :expiration_month, maxlength: 2 %>
      </div>

      <div class="field columns medium-4">
        <%= f.label "Ano", class: "text-subhead" %>
        <%= f.text_field :expiration_year, maxlength: 2 %>
      </div>

      <div class="field columns medium-4">
        <%= f.label "CVC", class: "text-subhead" %>
        <%= f.text_field :cvc, maxlength: 3 %>
      </div>
    </div>

    <div class="field">
      <%= f.label "Nome", class: "text-subhead" %>
      <%= f.text_field :holder_name %>
    </div>

    <div class="field date">
      <%= f.label "Nascimento", class: "text-subhead" %>
      <%= f.date_select :holder_birthdate, start_year: Date.current.year - 18, end_year: 1920, order: [:day, :month, :year] %>
    </div>

    <div class="field">
      <%= f.label "CPF", class: "text-subhead" %>
      <%= f.text_field :cpf, maxlength: 11 %>
    </div>

    <div class="row">
      <div class="field medium-6 columns">
        <%= f.label "Telefone", class: "text-subhead" %>
        <%= f.text_field :phone, maxlength: 11 %>
      </div>

      <div class="field medium-6 columns">
        <%= f.label "Parcelas", class: "text-subhead" %>
        <%= f.select :instalment_count, Payment::INSTALMENTS %>
      </div>
    </div>
    <%= hidden_field_tag "payment[order]", "#{@order.id}" %>
    <div class="actions">
      <%= f.submit 'Pagar', class: 'raised-button ink' %>
    </div>
  <% end %>
</div>

app/views/checkout/_form_customer.html.erb
<div class="columns medium-6 card end">
  <%= form_for :customer do |f| %>
    <div class="field">
      <%= f.label "Nome Completo", class: "text-subhead" %>
      <%= f.text_field :fullname %>
    </div>

    <div class="field">
      <%= f.label "E-mail", class: "text-subhead" %>
      <%= f.text_field :email %>
    </div>

    <div class="row">
      <div class="field medium-6 columns">
        <%= f.label "Telefone", class: "text-subhead" %>
        <%= f.text_field :phone, maxlength: 11 %>
      </div>

      <div class="field medium-6 columns">
        <%= f.label "CPF", class: "text-subhead" %>
        <%= f.text_field :tax_document, maxlength: 11 %>
      </div>
    </div>

    <div class="field date">
      <%= f.label "Nascimento", class: "text-subhead" %>
      <%= f.date_select :birth_date, :start_year => Date.current.year - 14, :end_year => 1920, order: [:day, :month, :year] %>
    </div>

    <div class="actions">
      <%= f.submit 'Cadastrar', class: 'raised-button ink' %>
    </div>
  <% end %>
</div>

app/views/checkout/confirm.html.erb
<% title 'Confirmação de Pagamento' %>
<div class="row confirm">
  <div class="columns card">
    <h1 class="text-display-1">Confirmação de Pagamento</h1>
    <div class="row">
      <div class="medium-6 columns">
        <div class="">
          <span class="text-title"><%= @customer.fullname %></span>
          <ul class="no-bullet">
            <li><%= @payment.external_id %></li>
            <% @product.each do |item| %>
            <li><%= item.product_name %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="medium-6 columns">
        <div class="text-right">
          <span class="text-display-1">R$ <%= BRL @payment.amount['total'] %></span>
        </div>
      </div>
    </div>
    <div class="row columns">
      <span class="text-subhead">Status do pagamento: <strong id="status"><%= Payment::STATUS[@payment.status] %></strong></span>
    </div>
  </div>
</div>
<script type="text/javascript">
  (function() {
      var count = 15,
          status = $('#status').text();

      setInterval(function() {
          if (status == 'Autorizado'){
            return
          }
        
          count -= 1;
          if (count == 0) {
            location.reload();
          }
      }, 1000);
  })();
</script>

app/views/checkout/customer.html.erb
<% title 'Cadastro' %>
<div class="row columns products">
  <h1>Identifique-se</h1>
  <%= render 'form_customer' %>
  <div class="columns medium-6 card end">
    <h3 class="text-center">Produtos</h3>
    <% total_price = 0 %>
    <% @products.each do |item| %>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span><%= item.product_name %></span></li>
              <li class="medium-3 columns"><span>R$ <%= BRL item.price %></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
      <% total_price += item.price %>
    <% end %>
      <hr>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span>Subtotal</span></li>
              <li class="medium-3 columns"><span>R$ <%= BRL total_price %></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
      <div class="field callout coupon">
        <label for="coupon"><strong>Cupom de desconto</strong></label>
        <%= text_field_tag :coupon %>
      </div>
  </div>
</div>

app/views/checkout/payment.html.erb
<% title 'Pagamento' %>
<div class="row columns card payment">
  <div class="medium-6 columns end">
    <h3 class="text-center">Pagamento</h3>
    <div class="customer columns">
      <ul class="no-bullet">
        <li class="text-title text-center"><%= @order_response.customer.fullname %></li>
        <li class="text-subhead text-center"><%= @order_response.customer.email %></li>
      </ul>
    </div>
    <div class="credit_card columns">
      <%= render 'form_card' %>
    </div>
  </div>
  <div class="columns medium-6 end">
    <h3 class="text-center">Produtos</h3>
    <hr>
    <% @order_response.items.each do |item| %>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span><%= item.product %></span></li>
              <li class="medium-3 columns"><span>R$ <span><%= BRL item.price %></span></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
    <% end %>
      <hr>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span>Adicional</span></li>
              <li class="medium-3 columns"><span>R$ <span data-initial="<%= @order_response.amount.subtotals.addition %>" id="addition"><%= BRL @order_response.amount.subtotals.addition %></span></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span>Desconto</span></li>
              <li class="medium-3 columns"><span>R$ <%= BRL @order_response.amount.subtotals.discount %></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
      <hr>
      <div class="columns end">
        <div class="row">
          <div class="columns">
            <ul class="no-bullet inline-list row">
              <li class="medium-9 columns"><span>Total</span></li>
              <li class="medium-3 columns"><span>R$ <span data-initial="<%= @order_response.amount.total %>" id="total"><%= BRL @order_response.amount.total %></span></span></li>
            </ul>
          </div>
        </div>
      </div>
      <hr>
  </div>
</div>